receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus-host:9090/write

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
