on:
  push:
    branches:
    - '**'
    tags:
    - '*'

name: Build / Release Docker Images

jobs:
  build-base:
    runs-on: ubuntu-22.04
    if: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build base
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: rafiki-base:latest
          outputs: type=docker,dest=/tmp/rafiki-base.tar
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rafiki-base
          path: /tmp/rafiki-base.tar
  build:
    runs-on: ubuntu-22.04
    needs: build-base
    if: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        package: [auth, backend, frontend]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rafiki-base
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/rafiki-base.tar
          docker image ls -a
      - name: Build
      - run: |
          docker build . \
            --file packages/${{ matrix.package }}/Dockerfile \


  build-multiplatform-base:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build base
        uses: docker/build-push-action@v4
        with:
          push: false
          image: rafiki-base:latest
          outputs: type=docker,dest=/tmp/rafiki-base.tar
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rafiki-base
          path: /tmp/rafiki-base.tar
  build-and-push:
    runs-on: ubuntu-22.04
    needs: build-multiplatform-base
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        package: [auth, backend, frontend]
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/rafiki-${{ matrix.package }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: rafiki-base
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/rafiki-base.tar
          docker image ls -a
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: packages/${{ matrix.package }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

